import Links from "@/components/parts/links/linksComponent";
import "@css/globals.css";

import dynamic from "next/dynamic";

const HeaderPart = dynamic(() => import("@/components/parts/header/header"), {
  ssr: false,
});

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderPart></HeaderPart>
        <Links></Links>
        <div>{children}</div>
      </body>
    </html>
  );
}
